name: Check

on:
  push:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Call setup_env action to setup workspace
      - uses: ./.github/actions/setup_env

      # Check for any formatting issues in the code.
      - run: dart format --set-exit-if-changed .

      # Statically analyze the Dart code for any errors.
      - run: dart analyze .

      # Run widget tests for our flutter project.
      # - run: flutter test